In [1]:
import torch

In [3]:
torch.__version__

'2.3.1'

## What is PyTorch?

* PyTorch is an open-source deep learning framework developed by Facebook's AI Research (FAIR) lab. It provides a flexible and efficient platform for building and training deep learning models. PyTorch is particularly popular for research and development because of its dynamic computation graph, which allows developers to modify the graph on-the-fly during execution.

#### Key features of PyTorch include:

* **Tensors**: Multidimensional arrays with GPU acceleration.
* **Autograd**: Automatic differentiation for dynamic computation graphs.
* **Torch.nn**: Modules for building neural networks.
* **Optimizers**: Tools for gradient-based optimization.
* **Data Loading Utilities**: Built-in support for handling datasets and creating data pipelines.

## 1. Creating Tensors

In [4]:
import numpy as np

In [6]:
array = np.array([1,2,3,4,5])
type(array)

numpy.ndarray

In [7]:
array.dtype

dtype('int32')

In [8]:
array

array([1, 2, 3, 4, 5])

In [10]:
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
# Creating a tensor from a Python list
tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(tensor)

tensor([[1., 2.],
        [3., 4.]])


In [12]:
# Creating a tensor with random values
random_tensor = torch.rand(2, 3)  # 2x3 matrix with values between 0 and 1
print(random_tensor)

tensor([[8.7352e-02, 5.4479e-04, 6.1771e-01],
        [5.1350e-01, 7.6746e-01, 7.3313e-01]])


In [13]:
# Tensor of zeros
zeros_tensor = torch.zeros(2, 3)  # 2x3 matrix with all elements as 0
print(zeros_tensor)

# Tensor of ones
ones_tensor = torch.ones(2, 3)  # 2x3 matrix with all elements as 1
print(ones_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## 2. Tensor Arithmetic

In [14]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Element-wise addition
sum_tensor = a + b
print("Sum:", sum_tensor)

Sum: tensor([5, 7, 9])


In [15]:
# Element-wise subtraction
diff_tensor = a - b
print("Difference:", diff_tensor)

Difference: tensor([-3, -3, -3])


In [16]:
# Element-wise multiplication
prod_tensor = a * b
print("Product:", prod_tensor)

Product: tensor([ 4, 10, 18])


In [18]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication
matrix_prod = torch.matmul(a, b)
print("Matrix product: \n", matrix_prod)

Matrix product: 
 tensor([[19, 22],
        [43, 50]])


## 3. Reshaping Tensors

In [20]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshaping to a different size
reshaped_tensor = tensor.view(3, 2)  # 3x2 tensor
print("Reshaped tensor:\n", reshaped_tensor)

Reshaped tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [21]:
# Flattening the tensor to a 1D vector
flattened_tensor = tensor.view(-1)
print("Flattened tensor:", flattened_tensor)

Flattened tensor: tensor([1, 2, 3, 4, 5, 6])


## 4. Slicing and Indexing

In [22]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Access a specific element
element = tensor[0, 1]  # First row, second column
print("Element:", element)

Element: tensor(2)


In [24]:
# Slice a part of the tensor
slice_tensor = tensor[:, 1:]  # All rows, from second column onward
print("Sliced tensor:\n", slice_tensor)

Sliced tensor:
 tensor([[2, 3],
        [5, 6]])


## 5. Tensor Concatenation

In [28]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

concat_tensor = torch.cat((a, b), dim=0)  # Concatenate along rows
print("Concatenated along rows:\n", concat_tensor)

Concatenated along rows:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [29]:
# Check if CUDA is available (i.e., if GPU is available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Using device: cpu
