In [1]:
import torch

In [2]:
torch.__version__

'2.3.1'

## What is PyTorch?

* PyTorch is an open-source deep learning framework developed by Facebook's AI Research (FAIR) lab. It provides a flexible and efficient platform for building and training deep learning models. PyTorch is particularly popular for research and development because of its dynamic computation graph, which allows developers to modify the graph on-the-fly during execution.

#### Key features of PyTorch include:

* **Tensors**: Multidimensional arrays with GPU acceleration.
* **Autograd**: Automatic differentiation for dynamic computation graphs.
* **Torch.nn**: Modules for building neural networks.
* **Optimizers**: Tools for gradient-based optimization.
* **Data Loading Utilities**: Built-in support for handling datasets and creating data pipelines.

## 1. Creating Tensors

In [3]:
import numpy as np

In [4]:
array = np.array([1,2,3,4,5])
type(array)

numpy.ndarray

In [5]:
array.dtype

dtype('int32')

In [6]:
array

array([1, 2, 3, 4, 5])

In [7]:
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [8]:
# Creating a tensor from a Python list
tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(tensor)

tensor([[1., 2.],
        [3., 4.]])


In [9]:
# Creating a tensor with random values
random_tensor = torch.rand(2, 3)  # 2x3 matrix with values between 0 and 1
print(random_tensor)

tensor([[0.6323, 0.9582, 0.2830],
        [0.3208, 0.0547, 0.2612]])


In [10]:
# Tensor of zeros
zeros_tensor = torch.zeros(2, 3)  # 2x3 matrix with all elements as 0
print(zeros_tensor)

# Tensor of ones
ones_tensor = torch.ones(2, 3)  # 2x3 matrix with all elements as 1
print(ones_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## 2. Tensor Arithmetic

In [11]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Element-wise addition
sum_tensor = a + b
print("Sum:", sum_tensor)

Sum: tensor([5, 7, 9])


In [12]:
# Element-wise subtraction
diff_tensor = a - b
print("Difference:", diff_tensor)

Difference: tensor([-3, -3, -3])


In [13]:
# Element-wise multiplication
prod_tensor = a * b
print("Product:", prod_tensor)

Product: tensor([ 4, 10, 18])


In [14]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication
matrix_prod = torch.matmul(a, b)
print("Matrix product: \n", matrix_prod)

Matrix product: 
 tensor([[19, 22],
        [43, 50]])


## 3. Reshaping Tensors

In [15]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Reshaping to a different size
reshaped_tensor = tensor.view(3, 2)  # 3x2 tensor
print("Reshaped tensor:\n", reshaped_tensor)

Reshaped tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [16]:
# Flattening the tensor to a 1D vector
flattened_tensor = tensor.view(-1)
print("Flattened tensor:", flattened_tensor)

Flattened tensor: tensor([1, 2, 3, 4, 5, 6])


## 4. Slicing and Indexing

In [17]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Access a specific element
element = tensor[0, 1]  # First row, second column
print("Element:", element)

Element: tensor(2)


In [18]:
# Slice a part of the tensor
slice_tensor = tensor[:, 1:]  # All rows, from second column onward
print("Sliced tensor:\n", slice_tensor)

Sliced tensor:
 tensor([[2, 3],
        [5, 6]])


## 5. Tensor Concatenation

In [19]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

concat_tensor = torch.cat((a, b), dim=0)  # Concatenate along rows
print("Concatenated along rows:\n", concat_tensor)

Concatenated along rows:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [20]:
# Check if CUDA is available (i.e., if GPU is available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Using device: cpu


#### Moving tensors to GPU:

In [21]:
# Move tensor to GPU
tensor_gpu = tensor.to(device)
print("Tensor on GPU:", tensor_gpu)

Tensor on GPU: tensor([[1, 2, 3],
        [4, 5, 6]])


### random tensor

In [29]:
# creating rondom tensor of size (3,4)
random_tensor=torch.rand(3,4)
print(random_tensor)

tensor([[0.7804, 0.2976, 0.6380, 0.6616],
        [0.8010, 0.7766, 0.2814, 0.4252],
        [0.3752, 0.7664, 0.3998, 0.1271]])


In [30]:
random_tensor[0,2]
random_tensor[2][3]

tensor(0.1271)

In [31]:
random_tensor.ndim

2

In [33]:
#creating image tensor with height, width and color channel
image_tensor = torch.rand(size=(3, 224,224)) # 3 color channels, 224x224 image
print(image_tensor)

tensor([[[0.3611, 0.4180, 0.7327],
         [0.7409, 0.0981, 0.7137],
         [0.3223, 0.0812, 0.4970],
         ...,
         [0.1273, 0.5102, 0.1866],
         [0.6871, 0.3355, 0.1984],
         [0.1748, 0.2814, 0.1097]],

        [[0.4889, 0.6480, 0.1263],
         [0.4818, 0.1061, 0.2676],
         [0.6377, 0.8582, 0.0543],
         ...,
         [0.6525, 0.4904, 0.0926],
         [0.7001, 0.3462, 0.3682],
         [0.8330, 0.9064, 0.6896]],

        [[0.9858, 0.1236, 0.1524],
         [0.2821, 0.6085, 0.2422],
         [0.3807, 0.5868, 0.2977],
         ...,
         [0.8413, 0.9297, 0.1328],
         [0.5697, 0.4044, 0.7414],
         [0.0047, 0.1777, 0.7397]],

        ...,

        [[0.4931, 0.7438, 0.4454],
         [0.9334, 0.0509, 0.3136],
         [0.1767, 0.8169, 0.4193],
         ...,
         [0.8922, 0.0564, 0.9778],
         [0.6191, 0.9842, 0.3849],
         [0.8275, 0.7099, 0.0665]],

        [[0.3393, 0.9749, 0.7797],
         [0.3651, 0.4507, 0.5613],
         [0.

In [37]:
print("the shape of your tensor is:",image_tensor.shape)# shape of the tensor
print ("the dimension of your tensor is:",image_tensor.ndim)# dimension of the tensor

the shape of your tensor is: torch.Size([224, 224, 3])
the dimension of your tensor is: 3


In [39]:
# range of values in the tensor
# range = torch.range(00,10)
range = torch.range(start= 1, step=2,end=100)
print(range)

tensor([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25., 27.,
        29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51., 53., 55.,
        57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77., 79., 81., 83.,
        85., 87., 89., 91., 93., 95., 97., 99.])


C:\Users\yitayew\AppData\Local\Temp\ipykernel_3708\4227904330.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(start= 1, step=2,end=100)


### Tensor data type

In the context of machine learning and deep learning, tensors are multi-dimensional arrays, serving as the fundamental data structure for neural network computations. They generalize matrices to higher dimensions and can represent scalars, vectors, matrices, or higher-dimensional data. Below are common tensor types and their explanations with examples:

1. Scalar (0-D Tensor)

    Description: A tensor with zero dimensions containing a single numerical value.
    Example:

In [41]:
scalar = torch.tensor(12)
print("values of the scallar",scalar)
print("items of the scallar",scalar.item())
print("data type of the scallar",scalar.dtype)
print("dimension of the scallar",scalar.ndim)
print("shape of the scallaer",scalar.shape)

values of the scallar tensor(12)
items of the scallar 12
data type of the scallar torch.int64
dimension of the scallar 0
shape of the scallaer torch.Size([])


2. Vector (1-D Tensor)

    Description: A one-dimensional array of values, often representing a sequence or a set of features.
    * Example:

In [49]:
# creating a vector
list = [1,2,3,4,5]
vector_data = torch.tensor(list)
print("the values of the vector",vector_data)
print("data type of the vector",vector_data.dtype)
print("shape the vector is:", vector_data.shape)

the values of the vector tensor([1, 2, 3, 4, 5])
data type of the vector torch.int64
shape the vector is: torch.Size([5])


3. Matrix (2-D Tensor)

    Description: A two-dimensional array, similar to a table with rows and columns.
    Example:

In [54]:
# creating a matrix
list2 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_vector = torch.tensor(list2)
print("the values of the matrix",matrix_vector)
print('the data type of the marics is:',matrix_vector.dtype)
print('the shape of the matrix is:',matrix_vector.shape)
print('the dimension of the matrix is:',matrix_vector.ndim)
print('the size of the matrix is:',matrix_vector.size())

the values of the matrix tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
the data type of the marics is: torch.int64
the shape of the matrix is: torch.Size([3, 3])
the dimension of the matrix is: 2
the size of the matrix is: torch.Size([3, 3])


4. 3-D Tensor

    Description: A tensor with three dimensions, often used to represent data like images (height × width × channels).
    Example:

In [67]:
# creating a 3D tensor
list3 = [[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]
tensor_3d = torch.tensor(list3)
print("the values of the 3D tensor\n",tensor_3d)
print('the data type of the 3D tensor is\n:',tensor_3d.dtype)
print('the shape of the 3D tensor is\n:',tensor_3d.shape)
print('the dimension of the 3D tensor is\n:',tensor_3d.ndim)
print('the size of the 3D tensor is\n:',tensor_3d.size())
print('the shape of the 3D tensor is\n:',tensor_3d.shape)

the values of the 3D tensor
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
the data type of the 3D tensor is
: torch.int64
the shape of the 3D tensor is
: torch.Size([2, 3, 3])
the dimension of the 3D tensor is
: 3
the size of the 3D tensor is
: torch.Size([2, 3, 3])
the shape of the 3D tensor is
: torch.Size([2, 3, 3])


5. N-Dimensional Tensor (N-D Tensor)

    Description: A tensor with more than three dimensions, often used in complex data like videos (time × height × width × channels) or higher-dimensional feature spaces.
    Example:

In [68]:
#create a 4D tensor
list4 = [[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]]
tensor_4d = torch.tensor(list4)
print("the values of the 4D tensor\n",tensor_4d)
print('the data type of the 4D tensor is\n:',tensor_4d.dtype)
print('the shape of the 4D tensor is\n:',tensor_4d.shape)
print('the dimension of the 4D tensor is\n:',tensor_4d.ndim)
print('the size of the 4D tensor is\n:',tensor_4d.size())
print('the shape of the 4D tensor is\n:',tensor_4d.shape)

the values of the 4D tensor
 tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])
the data type of the 4D tensor is
: torch.int64
the shape of the 4D tensor is
: torch.Size([2, 2, 2, 2])
the dimension of the 4D tensor is
: 4
the size of the 4D tensor is
: torch.Size([2, 2, 2, 2])
the shape of the 4D tensor is
: torch.Size([2, 2, 2, 2])
